<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Sale;
use App\Models\Product;
use App\Models\StockMovement;
use App\Models\Stock;
use App\Models\Category;
use App\Models\Customer;
use App\Models\PaymentMethod;
use App\Models\Currency;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Auth;


// FPDF
// require_once(base_path('vendor/setasign/fpdf/fpdf.php'));

class SalesPdfReportController extends Controller
{
    // Color scheme - Matisse theme (matches your brand)
    private $colors = [
        'matisse' => [36, 116, 172],      // #2474ac - Primary blue
        'sun' => [252, 172, 28],          // #fcac1c - Accent orange
        'hippie_blue' => [88, 154, 175],  // #589aaf - Secondary blue
        'text_dark' => [51, 51, 51],      // #333333 - Dark text
        'text_light' => [102, 102, 102],  // #666666 - Light text
        'success' => [40, 167, 69],       // #28a745 - Green
        'danger' => [220, 53, 69],        // #dc3545 - Red
        'warning' => [255, 193, 7],       // #ffc107 - Yellow
        'gray_light' => [248, 249, 250],  // #f8f9fa - Light gray
        'gray_medium' => [233, 236, 239], // #e9ecef - Medium gray
        'white' => [255, 255, 255]        // #ffffff - White
    ];

    private $logoPath;

    // French Translations
    private $translations = [
        'DAILY SALES REPORT' => 'RAPPORT DES VENTES QUOTIDIENNES',
        'Payment Method' => 'Mode de Paiement',
        'Transactions' => 'Transactions',
        'Total Amount' => 'Montant Total',
        'PAYMENT METHOD BREAKDOWN' => 'REPARTITION PAR MODE DE PAIEMENT',
        'TOP 10 SELLING PRODUCTS' => 'TOP 10 DES PRODUITS VENDUS',
        'Product Name' => 'Nom du Produit',
        'Qty Sold' => 'Qte Vendue',
        'Revenue' => 'Revenu',
        'SALES DETAILS' => 'DETAILS DES VENTES',
        'Sale No.' => 'N Vente',
        'Date/Time' => 'Date/Heure',
        'Customer' => 'Client',
        'Cashier' => 'Caissier',
        'Type' => 'Type',
        'Status' => 'Statut',
        'Items' => 'Articles',
        'Amount' => 'Montant',
        'DAILY BREAKDOWN' => 'REPARTITION QUOTIDIENNE',
        'Date' => 'Date',
        'PAYMENT TYPE ANALYSIS' => 'ANALYSE PAR TYPE DE PAIEMENT',
        'Payment Type' => 'Type de Paiement',
        'No sales transactions found for this period.' => 'Aucune transaction de vente trouvee pour cette periode.',
        'Generated by' => 'Genere par',
        'Page' => 'Page',
        'This is a computer-generated document and requires no signature' => 'Ceci est un document genere par ordinateur et ne necessite aucune signature',
        'Total Sales' => 'Ventes Totales',
        'Total Tax' => 'Taxe Totale',
        'Total Discount' => 'Remise Totale',
        'Subtotal' => 'Sous-total',
        'Average Sale' => 'Vente Moyenne',
        'Total Items' => 'Total Articles',
        'Cash Sales' => 'Ventes Cash',
        'Credit Sales' => 'Ventes Credit',
        'Unknown' => 'Inconnu',
        'Walk-in' => 'Client de passage',
        'SALES SUMMARY REPORT' => 'RAPPORT RECAPITULATIF DES VENTES',
        'KEY PERFORMANCE INDICATORS' => 'INDICATEURS CLES DE PERFORMANCE',
        'TOTAL REVENUE' => 'REVENU TOTAL',
        'AVERAGE SALE' => 'VENTE MOYENNE',
        'CASH SALES' => 'VENTES CASH',
        'CREDIT SALES' => 'VENTES CREDIT',
        'TAX COLLECTED' => 'TAXE PERCUE',
        'DISCOUNTS' => 'REMISES',
        'AVG SALE' => 'VENTE MOY.',
        'ITEMS SOLD' => 'ARTICLES VENDUS',
        'TOTAL SALES' => 'TOTAL VENTES',
        'SUMMARY OVERVIEW' => 'RESUME',
        'Filters: All Sales' => 'Filtres: Toutes les Ventes',
        'From' => 'De',
        'transactions' => 'transactions',
        'Per transaction' => 'Par transaction',
        // Shift Report Translations
        'SHIFT SALES REPORT' => 'RAPPORT DES VENTES DE QUART',
        'SHIFT SUMMARY' => 'RESUME DU QUART',
        'PAYMENT METHODS' => 'MODES DE PAIEMENT',
        'TOP PRODUCTS THIS SHIFT' => 'MEILLEURS PRODUITS DU QUART',
        'SALES TRANSACTIONS' => 'TRANSACTIONS DE VENTE',
        'CASHIER' => 'CAISSIER',
        'No sales transactions during this shift.' => 'Aucune transaction de vente pendant ce quart.',
        'Sale #' => 'N Vente',
        'Time' => 'Heure',
        'Qty' => 'Qte',
        'Method' => 'Methode',
        'Count' => 'Nombre',
        'Product' => 'Produit',
        // New shift metrics
        'TOTAL TRANSACTIONS' => 'TOTAL TRANSACTIONS',
        'EXPENSES' => 'DEPENSES',
        'CREDIT AMOUNT' => 'MONTANT CREDIT',
        'SALES TOTAL' => 'TOTAL VENTES',
        'BALANCE' => 'SOLDE'
    ];

    private function translate($key)
    {
        return $this->translations[$key] ?? $key;
    }

    public function __construct()
    {
        $this->logoPath = public_path('images/company/logo.png');
    }

    /**
     * =====================================================
     * REPORT 1: COMPREHENSIVE DAILY SALES REPORT
     * =====================================================
     * Full sales report with all details, filters, and breakdowns
     */
    public function generateDailySalesReport(Request $request)
    {
        try {
            $validator = Validator::make($request->all(), [
                'start_date' => 'required|date',
                'end_date' => 'required|date|after_or_equal:start_date',
                'branch_id' => 'nullable|exists:branches,id',
                'business_id' => 'nullable|exists:businesses,id',
                'customer_id' => 'nullable|exists:customers,id',
                'payment_type' => 'nullable|in:cash,credit,mixed',
                'payment_status' => 'nullable|in:paid,unpaid,partial',
                'status' => 'nullable|in:completed,pending,cancelled',
                'cashier_id' => 'nullable|exists:users,id',
                'payment_method_id' => 'nullable|exists:payment_methods,id',
                'category_id' => 'nullable|exists:categories,id',
                'product_id' => 'nullable|exists:products,id',
                'currency_code' => 'nullable|string|size:3',
            ]);

            if ($validator->fails()) {
                return validationErrorResponse($validator->errors());
            }

            $reportData = $this->getDailySalesReportData($request);
            return $this->generateDailySalesPDF($reportData);

        } catch (\Exception $e) {
            Log::error('Failed to generate daily sales report PDF', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString()
            ]);
            return serverErrorResponse('Failed to generate PDF report', $e->getMessage());
        }
    }

    /**
     * Get daily sales data with comprehensive filtering
     */
    private function getDailySalesReportData(Request $request)
    {
        $user = Auth::user();

        // Get currency information
        $currencyCode = $request->currency_code ?? $user->business->default_currency ?? 'USD';
        $currency = Currency::where('code', $currencyCode)->first();
        $currencySymbol = $currency ? $currency->symbol : '$';

        // Build query
        $query = Sale::with([
            'customer',
            'cashier',
            'branch',
            'business',
            'items.product.category',
            'salePayments.payment.paymentMethod'
        ]);

        $businessId = $request->business_id ?? $user->business_id;
        $branchId = $request->branch_id ?? $user->primary_branch_id;

        $query->where('business_id', $businessId);
        if ($branchId) {
            $query->where('branch_id', $branchId);
        }

        // Fix Date filtering to include pending sales
        $query->where(function ($q) use ($request) {
            $q->whereDate('completed_at', '>=', $request->start_date)
                ->whereDate('completed_at', '<=', $request->end_date)
                ->orWhere(function ($sub) use ($request) {
                    $sub->whereNull('completed_at')
                        ->whereDate('created_at', '>=', $request->start_date)
                        ->whereDate('created_at', '<=', $request->end_date);
                });
        });

        // Apply all filters
        if ($request->customer_id)
            $query->where('customer_id', $request->customer_id);
        if ($request->payment_type)
            $query->where('payment_type', $request->payment_type);
        if ($request->payment_status)
            $query->where('payment_status', $request->payment_status);
        if ($request->status)
            $query->where('status', $request->status);
        if ($request->cashier_id)
            $query->where('user_id', $request->cashier_id);

        if ($request->product_id) {
            $query->whereHas('items', fn($q) => $q->where('product_id', $request->product_id));
        }

        if ($request->category_id) {
            $query->whereHas('items.product', fn($q) => $q->where('category_id', $request->category_id));
        }

        if ($request->payment_method_id) {
            $query->whereHas('salePayments.payment', fn($q) => $q->where('payment_method_id', $request->payment_method_id));
        }

        $query->orderBy('completed_at', 'desc');
        $sales = $query->get();

        // Calculate comprehensive metrics
        $summary = [
            'total_sales' => $sales->count(),
            'total_amount' => $sales->sum('total_amount'),
            'total_tax' => $sales->sum('tax_amount'),
            'total_discount' => $sales->sum('discount_amount'),
            'subtotal' => $sales->sum('subtotal'),
            'cash_sales_count' => $sales->where('payment_type', 'cash')->count(),
            'credit_sales_count' => $sales->where('payment_type', 'credit')->count(),
            'cash_sales_amount' => $sales->where('payment_type', 'cash')->sum('total_amount'),
            'credit_sales_amount' => $sales->where('payment_type', 'credit')->sum('total_amount'),
            'average_sale' => $sales->count() > 0 ? $sales->sum('total_amount') / $sales->count() : 0,
            'total_items_sold' => $sales->sum(fn($sale) => $sale->items->sum('quantity')),
        ];

        // Payment method breakdown
        $paymentMethods = [];
        foreach ($sales as $sale) {
            foreach ($sale->salePayments as $sp) {
                $method = $sp->payment->paymentMethod->name ?? 'Unknown';
                if (!isset($paymentMethods[$method])) {
                    $paymentMethods[$method] = ['count' => 0, 'amount' => 0];
                }
                $paymentMethods[$method]['count']++;
                $paymentMethods[$method]['amount'] += $sp->amount;
            }
        }

        // Top products
        $productSales = [];
        foreach ($sales as $sale) {
            foreach ($sale->items as $item) {
                $pid = $item->product_id;
                if (!isset($productSales[$pid])) {
                    $productSales[$pid] = [
                        'product' => $item->product,
                        'quantity' => 0,
                        'amount' => 0
                    ];
                }
                $productSales[$pid]['quantity'] += $item->quantity;
                $productSales[$pid]['amount'] += $item->line_total;
            }
        }
        usort($productSales, fn($a, $b) => $b['quantity'] <=> $a['quantity']);
        $topProducts = array_slice($productSales, 0, 10);

        return [
            'sales' => $sales,
            'summary' => $summary,
            'payment_methods' => $paymentMethods,
            'top_products' => $topProducts,
            'currency' => $currencySymbol,
            'currency_code' => $currencyCode,
            'filters' => [
                'start_date' => $request->start_date,
                'end_date' => $request->end_date,
                'branch_id' => $branchId,
            ],
            'business' => $user->business,
            'branch' => $branchId ? $user->primaryBranch : null,
            'generated_by' => $user->name,
            'generated_at' => now()->format('Y-m-d H:i:s'),
        ];
    }

    /**
     * Generate beautiful daily sales PDF
     */
    private function generateDailySalesPDF($data)
    {
        $pdf = new \FPDF('L', 'mm', 'A4');
        $pdf->SetAutoPageBreak(true, 15);
        $pdf->AddPage();

        $primary = $this->colors['matisse'];
        $accent = $this->colors['sun'];

        // HEADER
        $this->addProfessionalHeader($pdf, $this->translate('DAILY SALES REPORT'), $data, $primary);

        // SUMMARY METRICS
        $this->addBeautifulSummaryBoxes($pdf, $data['summary'], $data['currency'], $primary, $accent);

        // PAYMENT BREAKDOWN
        if (!empty($data['payment_methods'])) {
            $this->addPaymentBreakdown($pdf, $data['payment_methods'], $data['currency'], $primary);
        }

        // TOP PRODUCTS
        if (!empty($data['top_products'])) {
            $this->addTopProducts($pdf, $data['top_products'], $data['currency'], $accent);
        }

        // SALES DETAILS TABLE
        $this->addSalesDetailsTable($pdf, $data['sales'], $data['currency'], $primary);

        // FOOTER
        $this->addProfessionalFooter($pdf, $data['generated_by'], $data['generated_at'], $data['business'], $data['branch']);

        $filename = 'rapport_ventes_quotidiennes_' . date('Y-m-d') . '.pdf';
        return response()->stream(
            fn() => print ($pdf->Output('S')),
            200,
            [
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'inline; filename="' . $filename . '"'
            ]
        );
    }

    /**
     * =====================================================
     * REPORT 2: SALES SUMMARY REPORT (COMPACT)
     * =====================================================
     * High-level executive summary - perfect for quick overview
     */
    public function generateSalesSummaryReport(Request $request)
    {
        try {
            $validator = Validator::make($request->all(), [
                'start_date' => 'required|date',
                'end_date' => 'required|date|after_or_equal:start_date',
                'branch_id' => 'nullable|exists:branches,id',
                'business_id' => 'nullable|exists:businesses,id',
                'currency_code' => 'nullable|string|size:3',
            ]);

            if ($validator->fails()) {
                return validationErrorResponse($validator->errors());
            }

            $reportData = $this->getSalesSummaryData($request);
            return $this->generateSalesSummaryPDF($reportData);

        } catch (\Exception $e) {
            Log::error('Failed to generate sales summary report', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString()
            ]);
            return serverErrorResponse('Failed to generate summary report', $e->getMessage());
        }
    }

    /**
     * Get sales summary data (aggregated metrics only)
     */
    private function getSalesSummaryData(Request $request)
    {
        $user = Auth::user();

        $currencyCode = $request->currency_code ?? $user->business->default_currency ?? 'USD';
        $currency = Currency::where('code', $currencyCode)->first();
        $currencySymbol = $currency ? $currency->symbol : '$';

        $businessId = $request->business_id ?? $user->business_id;
        $branchId = $request->branch_id ?? $user->primary_branch_id;

        // Get sales with minimal relationships
        $query = Sale::where('business_id', $businessId);

        if ($branchId) {
            $query->where('branch_id', $branchId);
        }

        // Fix Date filtering to include pending sales
        $query->where(function ($q) use ($request) {
            $q->whereDate('completed_at', '>=', $request->start_date)
                ->whereDate('completed_at', '<=', $request->end_date)
                ->orWhere(function ($sub) use ($request) {
                    $sub->whereNull('completed_at')
                        ->whereDate('created_at', '>=', $request->start_date)
                        ->whereDate('created_at', '<=', $request->end_date);
                });
        });

        $sales = $query->get();

        // Aggregate metrics
        $metrics = [
            'total_sales' => $sales->count(),
            'total_revenue' => $sales->sum('total_amount'),
            'total_tax' => $sales->sum('tax_amount'),
            'total_discount' => $sales->sum('discount_amount'),
            'avg_sale_value' => $sales->count() > 0 ? $sales->sum('total_amount') / $sales->count() : 0,
            'cash_sales' => $sales->where('payment_type', 'cash')->count(),
            'credit_sales' => $sales->where('payment_type', 'credit')->count(),
            'cash_amount' => $sales->where('payment_type', 'cash')->sum('total_amount'),
            'credit_amount' => $sales->where('payment_type', 'credit')->sum('total_amount'),
            'completed_sales' => $sales->where('status', 'completed')->count(),
            'cancelled_sales' => $sales->where('status', 'cancelled')->count(),
        ];

        // Sales by day
        $dailySales = $sales->groupBy(fn($sale) => $sale->completed_at->format('Y-m-d'))
            ->map(fn($group) => [
                'date' => $group->first()->completed_at->format('M d, Y'),
                'count' => $group->count(),
                'amount' => $group->sum('total_amount')
            ])->values();

        // Sales by payment type
        $byPaymentType = [
            ['type' => 'Cash', 'count' => $metrics['cash_sales'], 'amount' => $metrics['cash_amount']],
            ['type' => 'Credit', 'count' => $metrics['credit_sales'], 'amount' => $metrics['credit_amount']],
        ];

        return [
            'metrics' => $metrics,
            'daily_sales' => $dailySales,
            'by_payment_type' => $byPaymentType,
            'currency' => $currencySymbol,
            'currency_code' => $currencyCode,
            'period' => [
                'start' => $request->start_date,
                'end' => $request->end_date,
            ],
            'business' => $user->business,
            'branch' => $branchId ? $user->primaryBranch : null,
            'generated_by' => $user->name,
            'generated_at' => now()->format('Y-m-d H:i:s'),
        ];
    }

    /**
     * Generate beautiful sales summary PDF
     */
    private function generateSalesSummaryPDF($data)
    {
        $pdf = new \FPDF('P', 'mm', 'A4');
        $pdf->SetAutoPageBreak(true, 25); // Increased bottom margin for footer
        $pdf->AddPage();

        $primary = $this->colors['matisse'];
        $accent = $this->colors['sun'];

        // HEADER
        $this->addProfessionalHeader($pdf, $this->translate('SALES SUMMARY REPORT'), $data, $primary);

        // KEY METRICS (LARGE BOXES) - Reduced spacing
        $this->addCompactExecutiveSummaryBoxes($pdf, $data['metrics'], $data['currency'], $primary, $accent);

        // DAILY BREAKDOWN TABLE - Reduced spacing
        $this->addCompactDailyBreakdown($pdf, $data['daily_sales'], $data['currency'], $primary);

        // PAYMENT TYPE ANALYSIS - Reduced spacing
        $this->addCompactPaymentTypeAnalysis($pdf, $data['by_payment_type'], $data['currency'], $accent);

        // FOOTER
        $this->addProfessionalFooter($pdf, $data['generated_by'], $data['generated_at'], $data['business'], $data['branch']);

        $filename = 'resume_ventes_' . date('Y-m-d') . '.pdf';
        return response()->stream(
            fn() => print ($pdf->Output('S')),
            200,
            [
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'inline; filename="' . $filename . '"'
            ]
        );
    }

    /**
     * Compact executive summary boxes for sales summary report
     */
    private function addCompactExecutiveSummaryBoxes($pdf, $metrics, $currency, $primary, $accent)
    {
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->SetTextColor($primary[0], $primary[1], $primary[2]);
        $pdf->Cell(0, 6, $this->translate('KEY PERFORMANCE INDICATORS'), 0, 1);
        $pdf->Ln(2);

        $boxW = 90;
        $boxH = 26;
        $gap = 10;
        $startX = 15;
        $y = $pdf->GetY();

        // Row 1
        $this->drawLargeMetricBox($pdf, $startX, $y, $boxW, $boxH, $this->translate('TOTAL REVENUE'), $currency . ' ' . number_format($metrics['total_revenue'], 2), 'From ' . $metrics['total_sales'] . ' transactions', $primary);
        $this->drawLargeMetricBox($pdf, $startX + $boxW + $gap, $y, $boxW, $boxH, $this->translate('AVERAGE SALE'), $currency . ' ' . number_format($metrics['avg_sale_value'], 2), 'Per transaction', $accent);

        // Row 2
        $y += $boxH + $gap;
        $this->drawLargeMetricBox($pdf, $startX, $y, $boxW, $boxH, $this->translate('CASH SALES'), number_format($metrics['cash_sales']) . ' transactions', $currency . ' ' . number_format($metrics['cash_amount'], 2), $this->colors['success']);
        $this->drawLargeMetricBox($pdf, $startX + $boxW + $gap, $y, $boxW, $boxH, $this->translate('CREDIT SALES'), number_format($metrics['credit_sales']) . ' transactions', $currency . ' ' . number_format($metrics['credit_amount'], 2), $this->colors['warning']);

        $pdf->SetY($y + $boxH + 6);
    }

    /**
     * Compact daily breakdown table
     */
    private function addCompactDailyBreakdown($pdf, $dailySales, $currency, $primary)
    {
        if ($dailySales->isEmpty()) {
            return;
        }

        $pdf->SetFont('Arial', 'B', 11);
        $pdf->SetTextColor($primary[0], $primary[1], $primary[2]);
        $pdf->Cell(0, 6, $this->translate('DAILY BREAKDOWN'), 0, 1);
        $pdf->Ln(1);

        $pdf->SetFillColor($primary[0], $primary[1], $primary[2]);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFont('Arial', 'B', 9);

        $pdf->Cell(70, 7, $this->translate('Date'), 1, 0, 'C', true);
        $pdf->Cell(55, 7, $this->translate('Transactions'), 1, 0, 'C', true);
        $pdf->Cell(65, 7, $this->translate('Total Amount') . ' (' . $currency . ')', 1, 1, 'C', true);

        $pdf->SetFont('Arial', '', 8);
        $pdf->SetTextColor(0, 0, 0);

        $fill = false;
        foreach ($dailySales as $day) {
            $pdf->SetFillColor($fill ? 245 : 255, $fill ? 245 : 255, $fill ? 245 : 255);
            $pdf->Cell(70, 6, $day['date'], 1, 0, 'L', $fill);
            $pdf->Cell(55, 6, number_format($day['count']), 1, 0, 'C', $fill);
            $pdf->Cell(65, 6, number_format($day['amount'], 2), 1, 1, 'R', $fill);
            $fill = !$fill;
        }

        $pdf->Ln(5);
    }

    /**
     * Compact payment type analysis
     */
    private function addCompactPaymentTypeAnalysis($pdf, $paymentTypes, $currency, $accent)
    {
        $pdf->SetFont('Arial', 'B', 11);
        $pdf->SetTextColor($accent[0], $accent[1], $accent[2]);
        $pdf->Cell(0, 6, $this->translate('PAYMENT TYPE ANALYSIS'), 0, 1);
        $pdf->Ln(1);

        $pdf->SetFillColor($accent[0], $accent[1], $accent[2]);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFont('Arial', 'B', 9);

        $pdf->Cell(63, 7, $this->translate('Payment Type'), 1, 0, 'C', true);
        $pdf->Cell(63, 7, $this->translate('Transactions'), 1, 0, 'C', true);
        $pdf->Cell(64, 7, $this->translate('Total Amount') . ' (' . $currency . ')', 1, 1, 'C', true);

        $pdf->SetFont('Arial', '', 8);
        $pdf->SetTextColor(0, 0, 0);

        $fill = false;
        foreach ($paymentTypes as $type) {
            $pdf->SetFillColor($fill ? 245 : 255, $fill ? 245 : 255, $fill ? 245 : 255);
            $pdf->Cell(63, 6, $type['type'], 1, 0, 'L', $fill);
            $pdf->Cell(63, 6, number_format($type['count']), 1, 0, 'C', $fill);
            $pdf->Cell(64, 6, number_format($type['amount'], 2), 1, 1, 'R', $fill);
            $fill = !$fill;
        }

        // No extra Ln() here - let footer handle spacing
    }

    // =====================================================
    // SHARED PDF COMPONENTS (Editable Canvas)
    // =====================================================

    /**
     * Professional header with logo and company info
     */
    private function addProfessionalHeader($pdf, $title, $data, $primary)
    {
        // Logo centered at top
        if (file_exists($this->logoPath)) {
            $pageWidth = $pdf->GetPageWidth();
            $logoWidth = 35;
            $logoX = ($pageWidth - $logoWidth) / 2;
            $pdf->Image($this->logoPath, $logoX, 10, $logoWidth);
            $pdf->SetY(30);
        } else {
            $pdf->SetY(15);
        }

        // Report title
        $pdf->SetFont('Arial', 'B', 20);
        $pdf->SetTextColor($primary[0], $primary[1], $primary[2]);
        $pdf->Cell(0, 10, $title, 0, 1, 'C');
        $pdf->Ln(2);

        // Period
        $pdf->SetFont('Arial', 'B', 11);
        $pdf->SetTextColor(0, 0, 0);
        $period = date('F d, Y', strtotime($data['period']['start'] ?? $data['filters']['start_date'])) .
            ' - ' .
            date('F d, Y', strtotime($data['period']['end'] ?? $data['filters']['end_date']));
        $pdf->Cell(0, 6, $period, 0, 1, 'C');

        // Subtitle
        $pdf->SetFont('Arial', '', 9);
        $pdf->SetTextColor(100, 100, 100);
        $pdf->Cell(0, 5, 'Filtres: Toutes les Ventes', 0, 1, 'C');

        $pdf->Ln(8);
    }

    /**
     * Beautiful summary boxes - 2x4 grid
     */
    private function addBeautifulSummaryBoxes($pdf, $summary, $currency, $primary, $accent)
    {
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->SetTextColor($primary[0], $primary[1], $primary[2]);
        $pdf->Cell(0, 7, 'RESUME', 0, 1);
        $pdf->Ln(2);

        $boxW = 65;
        $boxH = 22;
        $gap = 5;
        $startX = 15;
        $y = $pdf->GetY();

        // Row 1
        $this->drawMetricBox($pdf, $startX, $y, $boxW, $boxH, $this->translate('TOTAL SALES'), number_format($summary['total_sales']), $primary);
        $this->drawMetricBox($pdf, $startX + ($boxW + $gap), $y, $boxW, $boxH, $this->translate('TOTAL REVENUE'), $currency . ' ' . number_format($summary['total_amount'], 2), $accent);
        $this->drawMetricBox($pdf, $startX + ($boxW + $gap) * 2, $y, $boxW, $boxH, $this->translate('AVG SALE'), $currency . ' ' . number_format($summary['average_sale'], 2), $this->colors['hippie_blue']);
        $this->drawMetricBox($pdf, $startX + ($boxW + $gap) * 3, $y, $boxW, $boxH, $this->translate('ITEMS SOLD'), number_format($summary['total_items_sold']), $this->colors['success']);

        // Row 2
        $y += $boxH + $gap;
        $this->drawMetricBox($pdf, $startX, $y, $boxW, $boxH, $this->translate('CASH SALES'), number_format($summary['cash_sales_count']) . ' (' . $currency . number_format($summary['cash_sales_amount'], 0) . ')', $this->colors['success']);
        $this->drawMetricBox($pdf, $startX + ($boxW + $gap), $y, $boxW, $boxH, $this->translate('CREDIT SALES'), number_format($summary['credit_sales_count']) . ' (' . $currency . number_format($summary['credit_sales_amount'], 0) . ')', $this->colors['warning']);
        $this->drawMetricBox($pdf, $startX + ($boxW + $gap) * 2, $y, $boxW, $boxH, $this->translate('TAX COLLECTED'), $currency . ' ' . number_format($summary['total_tax'], 2), $primary);
        $this->drawMetricBox($pdf, $startX + ($boxW + $gap) * 3, $y, $boxW, $boxH, $this->translate('DISCOUNTS'), $currency . ' ' . number_format($summary['total_discount'], 2), $this->colors['danger']);

        $pdf->SetY($y + $boxH + 8);
    }

    /**
     * Executive summary boxes (larger, 2x2 grid)
     */
    private function addExecutiveSummaryBoxes($pdf, $metrics, $currency, $primary, $accent)
    {
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->SetTextColor($primary[0], $primary[1], $primary[2]);
        $pdf->Cell(0, 7, 'KEY PERFORMANCE INDICATORS', 0, 1);
        $pdf->Ln(2);

        $boxW = 90;
        $boxH = 28;
        $gap = 10;
        $startX = 15;
        $y = $pdf->GetY();

        // Row 1
        $this->drawLargeMetricBox($pdf, $startX, $y, $boxW, $boxH, 'TOTAL REVENUE', $currency . ' ' . number_format($metrics['total_revenue'], 2), 'From ' . $metrics['total_sales'] . ' transactions', $primary);
        $this->drawLargeMetricBox($pdf, $startX + $boxW + $gap, $y, $boxW, $boxH, 'AVERAGE SALE', $currency . ' ' . number_format($metrics['avg_sale_value'], 2), 'Per transaction', $accent);

        // Row 2
        $y += $boxH + $gap;
        $this->drawLargeMetricBox($pdf, $startX, $y, $boxW, $boxH, 'CASH SALES', number_format($metrics['cash_sales']) . ' transactions', $currency . ' ' . number_format($metrics['cash_amount'], 2), $this->colors['success']);
        $this->drawLargeMetricBox($pdf, $startX + $boxW + $gap, $y, $boxW, $boxH, 'CREDIT SALES', number_format($metrics['credit_sales']) . ' transactions', $currency . ' ' . number_format($metrics['credit_amount'], 2), $this->colors['warning']);

        $pdf->SetY($y + $boxH + 8);
    }

    /**
     * Standard metric box
     */
    private function drawMetricBox($pdf, $x, $y, $w, $h, $title, $value, $color)
    {
        $pdf->SetDrawColor($color[0], $color[1], $color[2]);
        $pdf->SetLineWidth(0.4);
        $pdf->Rect($x, $y, $w, $h, 'D');

        $pdf->SetFont('Arial', 'B', 8);
        $pdf->SetTextColor($color[0], $color[1], $color[2]);
        $pdf->SetXY($x, $y + 3);
        $pdf->Cell($w, 5, $title, 0, 0, 'C');

        $pdf->SetFont('Arial', 'B', 12);
        $pdf->SetXY($x, $y + 11);
        $pdf->Cell($w, 6, $value, 0, 0, 'C');
    }

    /**
     * Large metric box (for executive summary)
     */
    private function drawLargeMetricBox($pdf, $x, $y, $w, $h, $title, $value, $subtitle, $color)
    {
        // Border
        $pdf->SetDrawColor($color[0], $color[1], $color[2]);
        $pdf->SetLineWidth(0.5);
        $pdf->Rect($x, $y, $w, $h, 'D');

        // Accent strip at top
        $pdf->SetFillColor($color[0], $color[1], $color[2]);
        $pdf->Rect($x, $y, $w, 3, 'F');

        // Title
        $pdf->SetFont('Arial', 'B', 9);
        $pdf->SetTextColor($color[0], $color[1], $color[2]);
        $pdf->SetXY($x, $y + 5);
        $pdf->Cell($w, 5, $title, 0, 0, 'C');

        // Value - Check length and adjust font
        $valueLength = strlen($value);
        if ($valueLength > 20) {
            $pdf->SetFont('Arial', 'B', 12);
        } elseif ($valueLength > 15) {
            $pdf->SetFont('Arial', 'B', 14);
        } else {
            $pdf->SetFont('Arial', 'B', 15);
        }

        $pdf->SetTextColor(0, 0, 0);
        $pdf->SetXY($x, $y + 12);
        $pdf->Cell($w, 7, $value, 0, 0, 'C');

        // Subtitle
        $pdf->SetFont('Arial', '', 8);
        $pdf->SetTextColor(100, 100, 100);
        $pdf->SetXY($x, $y + 21);
        $pdf->Cell($w, 4, $subtitle, 0, 0, 'C');
    }

    /**
     * Payment method breakdown table
     */
    private function addPaymentBreakdown($pdf, $methods, $currency, $primary)
    {
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->SetTextColor($primary[0], $primary[1], $primary[2]);
        $pdf->Cell(0, 7, $this->translate('PAYMENT METHOD BREAKDOWN'), 0, 1);
        $pdf->Ln(2);

        $tableWidth = 280; // Same as card width
        $pdf->SetFillColor($primary[0], $primary[1], $primary[2]);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFont('Arial', 'B', 9);

        $pdf->Cell(140, 8, $this->translate('Payment Method'), 1, 0, 'C', true);
        $pdf->Cell(70, 8, $this->translate('Transactions'), 1, 0, 'C', true);
        $pdf->Cell(70, 8, $this->translate('Total Amount') . ' (' . $currency . ')', 1, 1, 'C', true);

        $pdf->SetFont('Arial', '', 9);
        $pdf->SetTextColor(0, 0, 0);

        $fill = false;
        foreach ($methods as $name => $data) {
            $pdf->SetFillColor($fill ? 245 : 255, $fill ? 245 : 255, $fill ? 245 : 255);
            $pdf->Cell(140, 7, $name, 1, 0, 'L', $fill);
            $pdf->Cell(70, 7, number_format($data['count']), 1, 0, 'C', $fill);
            $pdf->Cell(70, 7, number_format($data['amount'], 2), 1, 1, 'R', $fill);
            $fill = !$fill;
        }

        $pdf->Ln(6);
    }

    /**
     * Top products table
     */
    private function addTopProducts($pdf, $products, $currency, $accent)
    {
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->SetTextColor($accent[0], $accent[1], $accent[2]);
        $pdf->Cell(0, 7, $this->translate('TOP 10 SELLING PRODUCTS'), 0, 1);
        $pdf->Ln(2);

        $pdf->SetFillColor($accent[0], $accent[1], $accent[2]);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFont('Arial', 'B', 9);

        $pdf->Cell(15, 8, '#', 1, 0, 'C', true);
        $pdf->Cell(155, 8, $this->translate('Product Name'), 1, 0, 'C', true);
        $pdf->Cell(55, 8, $this->translate('Qty Sold'), 1, 0, 'C', true);
        $pdf->Cell(55, 8, $this->translate('Revenue') . ' (' . $currency . ')', 1, 1, 'C', true);

        $pdf->SetFont('Arial', '', 8);
        $pdf->SetTextColor(0, 0, 0);

        $fill = false;
        $rank = 1;
        foreach ($products as $p) {
            $pdf->SetFillColor($fill ? 245 : 255, $fill ? 245 : 255, $fill ? 245 : 255);
            $pdf->Cell(15, 7, $rank, 1, 0, 'C', $fill);
            $pdf->Cell(155, 7, substr($p['product']->name ?? 'Unknown', 0, 60), 1, 0, 'L', $fill);
            $pdf->Cell(55, 7, number_format($p['quantity'], 2), 1, 0, 'C', $fill);
            $pdf->Cell(55, 7, number_format($p['amount'], 2), 1, 1, 'R', $fill);
            $fill = !$fill;
            $rank++;
        }

        $pdf->Ln(6);
    }

    /**
     * Sales details table (landscape)
     */
    private function addSalesDetailsTable($pdf, $sales, $currency, $primary)
    {
        if ($sales->isEmpty()) {
            $pdf->SetFont('Arial', 'I', 11);
            $pdf->SetTextColor(128, 128, 128);
            $pdf->Cell(0, 10, 'Aucune transaction de vente trouvee pour cette periode.', 0, 1, 'C');
            return;
        }

        $pdf->SetFont('Arial', 'B', 12);
        $pdf->SetTextColor($primary[0], $primary[1], $primary[2]);
        $pdf->Cell(0, 7, $this->translate('SALES DETAILS'), 0, 1);
        $pdf->Ln(2);

        $pdf->SetFillColor($primary[0], $primary[1], $primary[2]);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFont('Arial', 'B', 8);

        $pdf->Cell(25, 8, $this->translate('Sale No.'), 1, 0, 'C', true);
        $pdf->Cell(28, 8, $this->translate('Date/Time'), 1, 0, 'C', true);
        $pdf->Cell(43, 8, $this->translate('Customer'), 1, 0, 'C', true);
        $pdf->Cell(40, 8, $this->translate('Cashier'), 1, 0, 'C', true);
        $pdf->Cell(25, 8, $this->translate('Type'), 1, 0, 'C', true);
        $pdf->Cell(27, 8, $this->translate('Status'), 1, 0, 'C', true);
        $pdf->Cell(22, 8, $this->translate('Items'), 1, 0, 'C', true);
        $pdf->Cell(40, 8, $this->translate('Amount') . ' (' . $currency . ')', 1, 1, 'C', true);

        $pdf->SetFont('Arial', '', 7);
        $pdf->SetTextColor(0, 0, 0);

        $fill = false;
        foreach ($sales as $sale) {
            $pdf->SetFillColor($fill ? 248 : 255, $fill ? 248 : 255, $fill ? 248 : 255);

            $saleNum = substr($sale->sale_number, -8);
            $dateTime = $sale->completed_at ? $sale->completed_at->format('m/d H:i') : $sale->created_at->format('m/d H:i');
            $customer = $sale->customer ? substr($sale->customer->name, 0, 20) : 'Client de passage';
            $cashier = substr($sale->cashier->name ?? 'N/A', 0, 20);

            $pdf->Cell(25, 7, $saleNum, 1, 0, 'C', $fill);
            $pdf->Cell(28, 7, $dateTime, 1, 0, 'C', $fill);
            $pdf->Cell(43, 7, $customer, 1, 0, 'L', $fill);
            $pdf->Cell(40, 7, $cashier, 1, 0, 'L', $fill);
            $pdf->Cell(25, 7, ucfirst($sale->payment_type), 1, 0, 'C', $fill);
            $pdf->Cell(27, 7, ucfirst($sale->payment_status), 1, 0, 'C', $fill);
            $pdf->Cell(22, 7, number_format($sale->items->sum('quantity')), 1, 0, 'C', $fill);
            $pdf->Cell(40, 7, number_format($sale->total_amount, 2), 1, 1, 'R', $fill);

            $fill = !$fill;

            if ($pdf->GetY() > 180) {
                $pdf->AddPage();
                // Repeat header
                $pdf->SetFillColor($primary[0], $primary[1], $primary[2]);
                $pdf->SetTextColor(255, 255, 255);
                $pdf->SetFont('Arial', 'B', 8);
                $pdf->Cell(25, 8, $this->translate('Sale No.'), 1, 0, 'C', true);
                $pdf->Cell(28, 8, $this->translate('Date/Time'), 1, 0, 'C', true);
                $pdf->Cell(43, 8, $this->translate('Customer'), 1, 0, 'C', true);
                $pdf->Cell(40, 8, $this->translate('Cashier'), 1, 0, 'C', true);
                $pdf->Cell(25, 8, $this->translate('Type'), 1, 0, 'C', true);
                $pdf->Cell(27, 8, $this->translate('Status'), 1, 0, 'C', true);
                $pdf->Cell(22, 8, $this->translate('Items'), 1, 0, 'C', true);
                $pdf->Cell(40, 8, $this->translate('Amount') . ' (' . $currency . ')', 1, 1, 'C', true);
                $pdf->SetFont('Arial', '', 7);
                $pdf->SetTextColor(0, 0, 0);
            }
        }
    }

    /**
     * Daily sales breakdown table
     */
    private function addDailySalesBreakdown($pdf, $dailySales, $currency, $primary)
    {
        if ($dailySales->isEmpty()) {
            return;
        }

        $pdf->SetFont('Arial', 'B', 12);
        $pdf->SetTextColor($primary[0], $primary[1], $primary[2]);
        $pdf->Cell(0, 7, $this->translate('DAILY BREAKDOWN'), 0, 1);
        $pdf->Ln(2);

        $pdf->SetFillColor($primary[0], $primary[1], $primary[2]);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFont('Arial', 'B', 10);

        $pdf->Cell(70, 8, $this->translate('Date'), 1, 0, 'C', true);
        $pdf->Cell(55, 8, $this->translate('Transactions'), 1, 0, 'C', true);
        $pdf->Cell(65, 8, $this->translate('Total Amount') . ' (' . $currency . ')', 1, 1, 'C', true);

        $pdf->SetFont('Arial', '', 9);
        $pdf->SetTextColor(0, 0, 0);

        $fill = false;
        foreach ($dailySales as $day) {
            $pdf->SetFillColor($fill ? 245 : 255, $fill ? 245 : 255, $fill ? 245 : 255);
            $pdf->Cell(70, 7, $day['date'], 1, 0, 'L', $fill);
            $pdf->Cell(55, 7, number_format($day['count']), 1, 0, 'C', $fill);
            $pdf->Cell(65, 7, number_format($day['amount'], 2), 1, 1, 'R', $fill);
            $fill = !$fill;
        }

        $pdf->Ln(6);
    }

    /**
     * Payment type analysis
     */
    private function addPaymentTypeAnalysis($pdf, $paymentTypes, $currency, $accent)
    {
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->SetTextColor($accent[0], $accent[1], $accent[2]);
        $pdf->Cell(0, 7, $this->translate('PAYMENT TYPE ANALYSIS'), 0, 1);
        $pdf->Ln(2);

        $pdf->SetFillColor($accent[0], $accent[1], $accent[2]);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFont('Arial', 'B', 10);

        $pdf->Cell(63, 8, $this->translate('Payment Type'), 1, 0, 'C', true);
        $pdf->Cell(63, 8, $this->translate('Transactions'), 1, 0, 'C', true);
        $pdf->Cell(64, 8, $this->translate('Amount') . ' (' . $currency . ')', 1, 1, 'C', true);

        $pdf->SetFont('Arial', '', 9);
        $pdf->SetTextColor(0, 0, 0);

        $fill = false;
        foreach ($paymentTypes as $type) {
            $pdf->SetFillColor($fill ? 245 : 255, $fill ? 245 : 255, $fill ? 245 : 255);
            $pdf->Cell(63, 7, $type['type'], 1, 0, 'L', $fill);
            $pdf->Cell(63, 7, number_format($type['count']), 1, 0, 'C', $fill);
            $pdf->Cell(64, 7, number_format($type['amount'], 2), 1, 1, 'R', $fill);
            $fill = !$fill;
        }

        $pdf->Ln(6);
    }

    /**
     * Professional footer
     */
    private function addProfessionalFooter($pdf, $generatedBy, $generatedAt, $business = null, $branch = null)
    {
        $pdf->SetY(-25);

        // Business and branch info
        if ($business || $branch) {
            $pdf->SetFont('Arial', 'B', 9);
            $pdf->SetTextColor(36, 116, 172); // Matisse blue
            $businessText = ($business ? $business->name : '') . ($branch ? ' - ' . $branch->name : '');
            $pdf->Cell(0, 5, $businessText, 0, 1, 'C');
        }

        $pdf->SetFont('Arial', 'I', 8);
        $pdf->SetTextColor(120, 120, 120);
        $pdf->Cell(0, 4, $this->translate('Generated by') . ': ' . $generatedBy . ' | ' . date('F d, Y h:i A', strtotime($generatedAt)), 0, 1, 'C');
        $pdf->Cell(0, 4, $this->translate('Page') . ' ' . $pdf->PageNo(), 0, 1, 'C');
        $pdf->Cell(0, 4, $this->translate('This is a computer-generated document and requires no signature'), 0, 1, 'C');
    }

    // =====================================================
    // REPORT 3: SHIFT SALES REPORT
    // =====================================================
    // Sales report for a specific shift (time period) and cashier

    /**
     * Generate shift sales report - for cashiers to see their shift sales
     */
    public function generateShiftSalesReport(Request $request)
    {
        try {
            $validator = Validator::make($request->all(), [
                'shift_date' => 'required|date',
                'start_time' => 'required|date_format:H:i',
                'end_time' => 'required|date_format:H:i|after:start_time',
                'cashier_id' => 'nullable|exists:users,id',
                'branch_id' => 'nullable|exists:branches,id',
                'business_id' => 'nullable|exists:businesses,id',
                'currency_code' => 'nullable|string|size:3',
            ]);

            if ($validator->fails()) {
                return validationErrorResponse($validator->errors());
            }

            $reportData = $this->getShiftSalesReportData($request);
            return $this->generateShiftSalesPDF($reportData);

        } catch (\Exception $e) {
            Log::error('Failed to generate shift sales report PDF', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString()
            ]);
            return serverErrorResponse('Failed to generate PDF report', $e->getMessage());
        }
    }

    /**
     * Get shift sales data with time-based filtering
     */
    private function getShiftSalesReportData(Request $request)
    {
        $user = Auth::user();

        // Get currency information
        $currencyCode = $request->currency_code ?? $user->business->default_currency ?? 'USD';
        $currency = Currency::where('code', $currencyCode)->first();
        $currencySymbol = $currency ? $currency->symbol : '$';

        // Build datetime range
        $shiftDate = $request->shift_date;
        $startDateTime = $shiftDate . ' ' . $request->start_time . ':00';
        $endDateTime = $shiftDate . ' ' . $request->end_time . ':00';

        // Default to current user if no cashier specified
        $cashierId = $request->cashier_id ?? $user->id;
        $cashier = \App\Models\User::find($cashierId);

        // Build query
        $query = Sale::with([
            'customer',
            'cashier',
            'branch',
            'business',
            'items.product.category',
            'salePayments.payment.paymentMethod'
        ]);

        $businessId = $request->business_id ?? $user->business_id;
        $branchId = $request->branch_id; // Only filter if explicitly provided

        $query->where('business_id', $businessId);
        if ($branchId) {
            $query->where('branch_id', $branchId);
        }

        // Filter by cashier only if specified (not "All Cashiers")
        $cashierIdForFilter = $request->cashier_id;
        if ($cashierIdForFilter) {
            $query->where('user_id', $cashierIdForFilter);
        }

        // Filter by datetime range (shift period)
        $query->where(function ($q) use ($startDateTime, $endDateTime) {
            $q->where(function ($sub) use ($startDateTime, $endDateTime) {
                $sub->whereNotNull('completed_at')
                    ->where('completed_at', '>=', $startDateTime)
                    ->where('completed_at', '<=', $endDateTime);
            })->orWhere(function ($sub) use ($startDateTime, $endDateTime) {
                $sub->whereNull('completed_at')
                    ->where('created_at', '>=', $startDateTime)
                    ->where('created_at', '<=', $endDateTime);
            });
        });

        $query->orderBy('completed_at', 'asc');
        $sales = $query->get();

        // Calculate shift metrics
        $totalAmount = $sales->sum('total_amount');
        $creditAmount = $sales->where('payment_type', 'credit')->sum('total_amount');

        // Query expenses from CashMovement (cash_out) for this shift period
        $expensesQuery = \App\Models\CashMovement::where('business_id', $businessId)
            ->where('movement_type', 'cash_out')
            ->where('movement_time', '>=', $startDateTime)
            ->where('movement_time', '<=', $endDateTime);

        // Filter by cashier if specified
        if ($cashierIdForFilter) {
            $expensesQuery->where('processed_by', $cashierIdForFilter);
        }

        if ($branchId) {
            $expensesQuery->where('branch_id', $branchId);
        }

        $totalExpenses = $expensesQuery->sum('amount');

        // Calculate balance: Sales Total - Credit - Expenses
        $salesBalance = $totalAmount - $creditAmount - $totalExpenses;

        $summary = [
            'total_transactions' => $sales->count(),
            'total_amount' => $totalAmount,
            'credit_amount' => $creditAmount,
            'expenses' => $totalExpenses,
            'sales_balance' => $salesBalance,
            'total_tax' => $sales->sum('tax_amount'),
            'total_discount' => $sales->sum('discount_amount'),
            'subtotal' => $sales->sum('subtotal'),
            'cash_sales_count' => $sales->where('payment_type', 'cash')->count(),
            'credit_sales_count' => $sales->where('payment_type', 'credit')->count(),
            'cash_sales_amount' => $sales->where('payment_type', 'cash')->sum('total_amount'),
            'credit_sales_amount' => $creditAmount,
            'average_sale' => $sales->count() > 0 ? $totalAmount / $sales->count() : 0,
            'total_items_sold' => $sales->sum(fn($sale) => $sale->items->sum('quantity')),
            'completed_sales' => $sales->where('status', 'completed')->count(),
            'cancelled_sales' => $sales->where('status', 'cancelled')->count(),
        ];

        // Payment method breakdown
        $paymentMethods = [];
        foreach ($sales as $sale) {
            foreach ($sale->salePayments as $sp) {
                $method = $sp->payment->paymentMethod->name ?? 'Unknown';
                if (!isset($paymentMethods[$method])) {
                    $paymentMethods[$method] = ['count' => 0, 'amount' => 0];
                }
                $paymentMethods[$method]['count']++;
                $paymentMethods[$method]['amount'] += $sp->amount;
            }
        }

        // Top products for this shift
        $productSales = [];
        foreach ($sales as $sale) {
            foreach ($sale->items as $item) {
                $pid = $item->product_id;
                if (!isset($productSales[$pid])) {
                    $productSales[$pid] = [
                        'product' => $item->product,
                        'quantity' => 0,
                        'amount' => 0
                    ];
                }
                $productSales[$pid]['quantity'] += $item->quantity;
                $productSales[$pid]['amount'] += $item->line_total;
            }
        }
        usort($productSales, fn($a, $b) => $b['quantity'] <=> $a['quantity']);
        $topProducts = array_slice($productSales, 0, 10);

        return [
            'sales' => $sales,
            'summary' => $summary,
            'payment_methods' => $paymentMethods,
            'top_products' => $topProducts,
            'currency' => $currencySymbol,
            'currency_code' => $currencyCode,
            'shift' => [
                'date' => $shiftDate,
                'start_time' => $request->start_time,
                'end_time' => $request->end_time,
            ],
            'cashier' => $cashier,
            'business' => $user->business,
            'branch' => $branchId ? $user->primaryBranch : null,
            'generated_by' => $user->name,
            'generated_at' => now()->format('Y-m-d H:i:s'),
        ];
    }

    /**
     * Generate shift sales PDF
     */
    private function generateShiftSalesPDF($data)
    {
        $pdf = new \FPDF('P', 'mm', 'A4');
        $pdf->SetAutoPageBreak(true, 25);
        $pdf->AddPage();

        $primary = $this->colors['matisse'];
        $accent = $this->colors['sun'];

        // HEADER with shift info
        $this->addShiftReportHeader($pdf, $data, $primary);

        // CASHIER INFO
        $this->addCashierInfoBox($pdf, $data['cashier'], $data['shift'], $primary);

        // SUMMARY METRICS
        $this->addShiftSummaryBoxes($pdf, $data['summary'], $data['currency'], $primary, $accent);

        // PAYMENT BREAKDOWN (if any payments)
        if (!empty($data['payment_methods'])) {
            $this->addShiftPaymentBreakdown($pdf, $data['payment_methods'], $data['currency'], $primary);
        }

        // TOP PRODUCTS (compact version)
        if (!empty($data['top_products'])) {
            $this->addShiftTopProducts($pdf, $data['top_products'], $data['currency'], $accent);
        }

        // SALES LIST
        $this->addShiftSalesTable($pdf, $data['sales'], $data['currency'], $primary);

        // Disable auto page break before adding footer to prevent empty page
        $pdf->SetAutoPageBreak(false);

        // FOOTER - add to current page
        $this->addProfessionalFooter($pdf, $data['generated_by'], $data['generated_at'], $data['business'], $data['branch']);

        $filename = 'shift_sales_report_' . $data['shift']['date'] . '_' . str_replace(':', '-', $data['shift']['start_time']) . '.pdf';
        return response()->stream(
            fn() => print ($pdf->Output('S')),
            200,
            [
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'inline; filename="' . $filename . '"'
            ]
        );
    }

    /**
     * Shift report header
     */
    private function addShiftReportHeader($pdf, $data, $primary)
    {
        // Logo centered at top
        if (file_exists($this->logoPath)) {
            $pageWidth = $pdf->GetPageWidth();
            $logoWidth = 35;
            $logoX = ($pageWidth - $logoWidth) / 2;
            $pdf->Image($this->logoPath, $logoX, 10, $logoWidth);
            $pdf->SetY(30);
        } else {
            $pdf->SetY(15);
        }

        $pdf->SetFont('Arial', 'B', 18);
        $pdf->SetTextColor($primary[0], $primary[1], $primary[2]);
        $pdf->Cell(0, 10, $this->translate('SHIFT SALES REPORT'), 0, 1, 'C');
        $pdf->Ln(2);

        // Shift date and time
        $pdf->SetFont('Arial', 'B', 11);
        $pdf->SetTextColor(0, 0, 0);
        $shiftInfo = date('F d, Y', strtotime($data['shift']['date'])) .
            ' | ' . date('h:i A', strtotime($data['shift']['start_time'])) .
            ' - ' . date('h:i A', strtotime($data['shift']['end_time']));
        $pdf->Cell(0, 6, $shiftInfo, 0, 1, 'C');

        $pdf->Ln(6);
    }

    /**
     * Cashier info box
     */
    private function addCashierInfoBox($pdf, $cashier, $shift, $primary)
    {
        $pdf->SetFillColor($primary[0], $primary[1], $primary[2]);
        $pdf->SetDrawColor($primary[0], $primary[1], $primary[2]);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFont('Arial', 'B', 10);

        $pdf->Cell(0, 8, '  ' . $this->translate('CASHIER') . ': ' . strtoupper($cashier->name ?? $this->translate('Unknown')), 1, 1, 'L', true);

        $pdf->SetTextColor(0, 0, 0);
        $pdf->Ln(4);
    }

    /**
     * Shift summary boxes - compact 2x3 grid
     */
    private function addShiftSummaryBoxes($pdf, $summary, $currency, $primary, $accent)
    {
        $pdf->SetFont('Arial', 'B', 11);
        $pdf->SetTextColor($primary[0], $primary[1], $primary[2]);
        $pdf->Cell(0, 6, $this->translate('SHIFT SUMMARY'), 0, 1);
        $pdf->Ln(2);

        $boxW = 58;
        $boxH = 22;
        $gap = 4;
        $startX = 12;
        $y = $pdf->GetY();

        // Row 1: Total Transactions, Sales Total, Credit Amount
        $this->drawMetricBox($pdf, $startX, $y, $boxW, $boxH, $this->translate('TOTAL TRANSACTIONS'), number_format($summary['total_transactions']), $primary);
        $this->drawMetricBox($pdf, $startX + ($boxW + $gap), $y, $boxW, $boxH, $this->translate('SALES TOTAL'), $currency . ' ' . number_format($summary['total_amount'], 2), $accent);
        $this->drawMetricBox($pdf, $startX + ($boxW + $gap) * 2, $y, $boxW, $boxH, $this->translate('CREDIT AMOUNT'), $currency . ' ' . number_format($summary['credit_amount'], 2), $this->colors['warning']);

        // Row 2: Expenses, Balance (highlighted)
        $y += $boxH + $gap;
        $this->drawMetricBox($pdf, $startX, $y, $boxW, $boxH, $this->translate('EXPENSES'), $currency . ' ' . number_format($summary['expenses'], 2), $this->colors['danger']);
        $this->drawMetricBox($pdf, $startX + ($boxW + $gap), $y, ($boxW * 2) + $gap, $boxH, $this->translate('BALANCE'), $currency . ' ' . number_format($summary['sales_balance'], 2), $this->colors['success']);

        $pdf->SetY($y + $boxH + 6);
    }

    /**
     * Shift payment breakdown - compact
     */
    private function addShiftPaymentBreakdown($pdf, $methods, $currency, $primary)
    {
        $pdf->SetFont('Arial', 'B', 10);
        $pdf->SetTextColor($primary[0], $primary[1], $primary[2]);
        $pdf->Cell(0, 6, $this->translate('PAYMENT METHODS'), 0, 1);
        $pdf->Ln(1);

        $pdf->SetFillColor($primary[0], $primary[1], $primary[2]);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFont('Arial', 'B', 8);

        $pdf->Cell(80, 6, $this->translate('Method'), 1, 0, 'C', true);
        $pdf->Cell(50, 6, $this->translate('Count'), 1, 0, 'C', true);
        $pdf->Cell(50, 6, $this->translate('Amount') . ' (' . $currency . ')', 1, 1, 'C', true);

        $pdf->SetFont('Arial', '', 8);
        $pdf->SetTextColor(0, 0, 0);

        $fill = false;
        foreach ($methods as $name => $data) {
            $pdf->SetFillColor($fill ? 245 : 255, $fill ? 245 : 255, $fill ? 245 : 255);
            $pdf->Cell(80, 5, $name, 1, 0, 'L', $fill);
            $pdf->Cell(50, 5, number_format($data['count']), 1, 0, 'C', $fill);
            $pdf->Cell(50, 5, number_format($data['amount'], 2), 1, 1, 'R', $fill);
            $fill = !$fill;
        }

        $pdf->Ln(4);
    }

    /**
     * Shift top products - compact
     */
    private function addShiftTopProducts($pdf, $products, $currency, $accent)
    {
        $pdf->SetFont('Arial', 'B', 10);
        $pdf->SetTextColor($accent[0], $accent[1], $accent[2]);
        $pdf->Cell(0, 6, $this->translate('TOP PRODUCTS THIS SHIFT'), 0, 1);
        $pdf->Ln(1);

        $pdf->SetFillColor($accent[0], $accent[1], $accent[2]);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFont('Arial', 'B', 8);

        $pdf->Cell(100, 6, $this->translate('Product'), 1, 0, 'C', true);
        $pdf->Cell(40, 6, $this->translate('Qty'), 1, 0, 'C', true);
        $pdf->Cell(40, 6, $this->translate('Amount') . ' (' . $currency . ')', 1, 1, 'C', true);

        $pdf->SetFont('Arial', '', 8);
        $pdf->SetTextColor(0, 0, 0);

        $fill = false;
        $count = 0;
        foreach ($products as $p) {
            if ($count >= 5)
                break; // Only top 5 for shift report
            $productName = $p['product']->name ?? $this->translate('Unknown');
            if (strlen($productName) > 40) {
                $productName = substr($productName, 0, 37) . '...';
            }
            $pdf->SetFillColor($fill ? 245 : 255, $fill ? 245 : 255, $fill ? 245 : 255);
            $pdf->Cell(100, 5, $productName, 1, 0, 'L', $fill);
            $pdf->Cell(40, 5, number_format($p['quantity']), 1, 0, 'C', $fill);
            $pdf->Cell(40, 5, number_format($p['amount'], 2), 1, 1, 'R', $fill);
            $fill = !$fill;
            $count++;
        }

        $pdf->Ln(4);
    }

    /**
     * Shift sales table - compact list
     */
    private function addShiftSalesTable($pdf, $sales, $currency, $primary)
    {
        $pdf->SetFont('Arial', 'B', 10);
        $pdf->SetTextColor($primary[0], $primary[1], $primary[2]);
        $pdf->Cell(0, 6, $this->translate('SALES TRANSACTIONS'), 0, 1);
        $pdf->Ln(1);

        if ($sales->isEmpty()) {
            $pdf->SetFont('Arial', 'I', 9);
            $pdf->SetTextColor(100, 100, 100);
            $pdf->Cell(0, 8, $this->translate('No sales transactions during this shift.'), 0, 1, 'C');
            return;
        }

        $pdf->SetFillColor($primary[0], $primary[1], $primary[2]);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFont('Arial', 'B', 7);

        // Adjusted column widths: Sale# wider (55), Time smaller (22), Customer (45), Items (20), Amount (38)
        $pdf->Cell(55, 6, $this->translate('Sale #'), 1, 0, 'C', true);
        $pdf->Cell(22, 6, $this->translate('Time'), 1, 0, 'C', true);
        $pdf->Cell(45, 6, $this->translate('Customer'), 1, 0, 'C', true);
        $pdf->Cell(20, 6, $this->translate('Items'), 1, 0, 'C', true);
        $pdf->Cell(38, 6, $this->translate('Amount') . ' (' . $currency . ')', 1, 1, 'C', true);

        $pdf->SetFont('Arial', '', 7);
        $pdf->SetTextColor(0, 0, 0);

        $fill = false;
        foreach ($sales as $sale) {
            // Check for page break
            if ($pdf->GetY() > 250) {
                $pdf->AddPage();
                $pdf->SetFillColor($primary[0], $primary[1], $primary[2]);
                $pdf->SetTextColor(255, 255, 255);
                $pdf->SetFont('Arial', 'B', 7);
                $pdf->Cell(55, 6, $this->translate('Sale #'), 1, 0, 'C', true);
                $pdf->Cell(22, 6, $this->translate('Time'), 1, 0, 'C', true);
                $pdf->Cell(45, 6, $this->translate('Customer'), 1, 0, 'C', true);
                $pdf->Cell(20, 6, $this->translate('Items'), 1, 0, 'C', true);
                $pdf->Cell(38, 6, $this->translate('Amount') . ' (' . $currency . ')', 1, 1, 'C', true);
                $pdf->SetFont('Arial', '', 7);
                $pdf->SetTextColor(0, 0, 0);
            }

            $time = $sale->completed_at ? date('h:i A', strtotime($sale->completed_at)) : date('h:i A', strtotime($sale->created_at));
            $customer = $sale->customer->name ?? $this->translate('Walk-in');
            if (strlen($customer) > 18) {
                $customer = substr($customer, 0, 15) . '...';
            }

            $pdf->SetFillColor($fill ? 245 : 255, $fill ? 245 : 255, $fill ? 245 : 255);
            $pdf->Cell(55, 5, $sale->sale_number, 1, 0, 'L', $fill);
            $pdf->Cell(22, 5, $time, 1, 0, 'C', $fill);
            $pdf->Cell(45, 5, $customer, 1, 0, 'L', $fill);
            $pdf->Cell(20, 5, $sale->items->sum('quantity'), 1, 0, 'C', $fill);
            $pdf->Cell(38, 5, number_format($sale->total_amount, 2), 1, 1, 'R', $fill);
            $fill = !$fill;
        }

        $pdf->Ln(4);
    }

}

